export const navMenus = [
  {
    id: 'cuentas',
    label: 'Cuentas',
    path: '/cuentas',
    groups: [
      {
        title: 'Ahorros',
        links: [
          { label: 'Ahorro Caja de los niños', path: '/productos/ahorro-ninos' },
          { label: 'Ahorro Caja juvenil', path: '/productos/ahorro-juvenil' },
          { label: 'Ahorro Caja en línea', path: '/productos/ahorro-en-linea' },
          { label: 'Ahorro regular', path: '/productos/ahorro-regular' },
          { label: 'Ahorro platinum', path: '/productos/ahorro-platinum' },
        ],
      },
      {
        title: 'Digitales',
        links: [
          { label: 'Digital Panamá para ti', path: '/productos/digital-panama' },
          { label: 'Digital infantil', path: '/productos/digital-infantil' },
          { label: 'Digital juvenil', path: '/productos/digital-juvenil' },
          { label: 'Digital navidad', path: '/productos/digital-navidad' },
        ],
      },
      {
        title: 'Otras',
        links: [
          { label: 'Cuenta corriente', path: '/productos/corriente-chequera' },
          { label: 'Plazo fijo', path: '/productos/plazo-fijo' },
          { label: 'Cuenta de Navidad', path: '/productos/cuenta-navidad' },
        ],
      },
    ],
  },
  {
    id: 'tarjetas',
    label: 'Tarjetas',
    path: '/tarjetas',
    groups: [
      {
        title: 'Crédito',
        links: [
          { label: 'Mastercard Clásica', path: '/productos/tc-clasica' },
          { label: 'Mastercard Oro', path: '/productos/tc-oro' },
          { label: 'Mastercard Platinum', path: '/productos/tc-platinum' },
        ],
      },
      {
        title: 'Débito y clave',
        links: [
          { label: 'Débito Mastercard', path: '/productos/td-mastercard' },
          { label: 'Tarjeta Clave', path: '/productos/td-clave' },
          { label: 'Débito juvenil', path: '/productos/td-juvenil' },
        ],
      },
    ],
  },
  {
    id: 'prestamos',
    label: 'Préstamos',
    path: '/prestamos',
    groups: [
      {
        title: 'Personales y prendarios',
        links: [
          { label: 'Préstamo personal', path: '/productos/prestamo-personal' },
          { label: 'Empleados públicos', path: '/productos/prestamo-publico' },
          { label: 'Empleados privados', path: '/productos/prestamo-privado' },
          { label: 'Préstamos prendarios', path: '/productos/prendario' },
        ],
      },
      {
        title: 'Vivienda',
        links: [
          { label: 'Casa Más', path: '/casa-mas' },
          { label: 'Hipoteca preferencial', path: '/productos/hipoteca-preferencial' },
          { label: 'Traslado de hipoteca', path: '/productos/traslado-hipoteca' },
          { label: 'Compra de terrenos', path: '/productos/terrenos' },
        ],
      },
      {
        title: 'Autos y verdes',
        links: [
          { label: 'Préstamo de auto', path: '/productos/auto' },
          { label: 'Auto ecológico', path: '/productos/auto-eco' },
          { label: 'Paneles solares', path: '/productos/paneles' },
        ],
      },
    ],
  },
  {
    id: 'seguros',
    label: 'Seguros y asistencias',
    path: '/seguros',
    groups: [
      {
        title: 'Protección',
        links: [
          { label: 'Seguro de vida', path: '/productos/seguro-vida' },
          { label: 'Seguro de incendio', path: '/productos/seguro-incendio' },
          { label: 'Seguro de auto', path: '/productos/seguro-auto' },
          { label: 'Asistencia médica', path: '/productos/asistencia-medica' },
        ],
      },
    ],
  },
  {
    id: 'propiedades',
    label: 'Propiedades',
    path: '/propiedades',
    groups: [
      {
        title: 'Catálogos',
        links: [
          { label: 'Bienes nuevos', path: '/propiedades?tipo=nuevas' },
          { label: 'Bienes reposeídos', path: '/propiedades?tipo=reposeidas' },
        ],
      },
    ],
  },
  {
    id: 'servicios',
    label: 'Servicios',
    path: '/servicios',
    groups: [
      {
        title: 'Canales',
        links: [
          { label: 'Banca en línea', path: '/banca-en-linea' },
          { label: 'App móvil', path: '/servicios#app' },
          { label: 'Sucursales y cajeros', path: '/servicios#sucursales' },
          { label: 'Transferencias ACH', path: '/servicios#ach' },
        ],
      },
    ],
  },
]

export const products = [
  {
    slug: 'ahorro-ninos',
    name: 'Ahorro Caja de los niños',
    category: 'cuentas',
    filter: 'ahorros',
    segment: 'personas',
    rate: 'Hasta 2.00%',
    summary: 'Enseña a tus hijos a ahorrar, planificar y alcanzar sus metas desde pequeños.',
    benefits: ['Hasta 2.00% de interés', 'Educación financiera temprana', 'Control parental'],
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'ahorro-juvenil',
    name: 'Ahorro Caja juvenil',
    category: 'cuentas',
    filter: 'ahorros',
    segment: 'personas',
    rate: 'Tarjeta débito',
    summary: 'Controla tus ahorros, invierte y compra fácilmente para alcanzar tus metas.',
    benefits: ['Tarjeta Mastercard Débito Juvenil', 'Descuentos en comercios', 'Compras nacionales e internacionales'],
    image: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'ahorro-en-linea',
    name: 'Ahorro Caja en línea',
    category: 'cuentas',
    filter: 'digitales',
    segment: 'personas',
    rate: 'Hasta 1.00%',
    summary: 'Ábrela sin monto mínimo y gestiona tus finanzas 24/7 desde cualquier dispositivo.',
    benefits: ['Sin monto de apertura', 'Tasa de hasta 1.00%', 'Apertura 100% en línea'],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'ahorro-regular',
    name: 'Ahorro regular',
    category: 'cuentas',
    filter: 'ahorros',
    segment: 'personas',
    rate: 'Flexible',
    summary: 'Planifica tu futuro y el de tu familia con una cuenta sólida y versátil.',
    benefits: ['Compras físicas y en línea', 'Afiliación a Caja en Línea', 'Sirve como garantía de préstamos'],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'ahorro-platinum',
    name: 'Ahorro platinum',
    category: 'cuentas',
    filter: 'ahorros',
    segment: 'personas',
    rate: 'Hasta 4.50%',
    summary: 'Maximiza tus ahorros con tasas competitivas y beneficios exclusivos.',
    benefits: ['Hasta 4.50% de interés', 'Transferencias nacionales e internacionales', 'Tarjeta débito a tu elección'],
    image: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'digital-panama',
    name: 'Digital Panamá para ti',
    category: 'cuentas',
    filter: 'digitales',
    segment: 'personas',
    rate: 'Desde B/. 25',
    summary: 'Cuenta digital con beneficios pensados para asegurar tu futuro financiero.',
    benefits: ['Apertura desde B/. 25.00', 'Movimientos mensuales hasta B/. 5,000', 'Débito Mastercard o Clave'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'digital-infantil',
    name: 'Digital infantil',
    category: 'cuentas',
    filter: 'digitales',
    segment: 'personas',
    rate: 'Desde B/. 2.50',
    summary: 'Facilita el ahorro de tus pequeños de forma rápida y segura.',
    benefits: ['Monto mínimo B/. 2.50', 'Movimientos hasta B/. 5,000', 'Caja en Línea incluida'],
    image: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'digital-juvenil',
    name: 'Digital juvenil',
    category: 'cuentas',
    filter: 'digitales',
    segment: 'personas',
    rate: 'Desde B/. 5',
    summary: 'Transacciones, ahorro y tarjeta Mastercard para jóvenes.',
    benefits: ['Apertura desde B/. 5.00', 'Movimientos hasta B/. 1,500', 'Tarjeta Mastercard'],
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'digital-navidad',
    name: 'Digital navidad',
    category: 'cuentas',
    filter: 'digitales',
    segment: 'personas',
    rate: '+2 semanas',
    summary: 'Ahorra en el año y recibe tu total en diciembre, con un incentivo especial.',
    benefits: ['Desembolso la primera semana de diciembre', 'Incentivo de 2 semanas adicionales', 'Ahorro semanal programado'],
    image: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'corriente-chequera',
    name: 'Corriente chequera',
    category: 'cuentas',
    filter: 'corrientes',
    segment: 'personas',
    rate: 'Chequera + débito',
    summary: 'Cuenta tradicional con chequera, débito Mastercard y compras seguras.',
    benefits: ['Manejo por chequera', 'Compras físicas y en línea', 'Caja en Línea'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'plazo-fijo',
    name: 'Plazo fijo',
    category: 'cuentas',
    filter: 'plazo',
    segment: 'personas',
    rate: '1 a 5 años',
    summary: 'Seguridad y rendimientos con plazos flexibles y pagos de interés a tu medida.',
    benefits: ['Plazos de 1 a 5 años', 'Pago mensual, trimestral o al vencimiento', 'Respaldo de Caja de Ahorros'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'cuenta-navidad',
    name: 'Cuenta de Navidad',
    category: 'cuentas',
    filter: 'ahorros',
    segment: 'personas',
    rate: '1 semana extra',
    summary: 'Prepárate para los gastos de fin de año con depósitos flexibles.',
    benefits: ['Semana extra al abrirla con libreta', 'Depósitos por ventanilla, ACH o Caja en Línea', 'Descuento directo disponible'],
    image: 'https://images.unsplash.com/photo-1482517967863-00e15c9b44be?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'ahorro-empresarial',
    name: 'Ahorro empresarial',
    category: 'cuentas',
    filter: 'empresariales',
    segment: 'empresas',
    rate: 'Alta liquidez',
    summary: 'Liquidez inmediata y gestión ágil de fondos para tu empresa.',
    benefits: ['Garantía para préstamos y tarjetas', 'Débito Mastercard', 'Caja en Línea comercial'],
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'corriente-empresarial',
    name: 'Corriente empresarial',
    category: 'cuentas',
    filter: 'empresariales',
    segment: 'empresas',
    rate: 'Cheques + digital',
    summary: 'Fondos con alta liquidez, chequera y operación en sucursales a nivel nacional.',
    benefits: ['Chequera empresarial', 'Caja en Línea comercial', 'Red nacional de sucursales'],
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'plazo-fijo-empresarial',
    name: 'Plazo fijo empresarial',
    category: 'cuentas',
    filter: 'empresariales',
    segment: 'empresas',
    rate: '1 a 5 años',
    summary: 'Invierte excedentes con seguridad y rendimientos a corto, mediano y largo plazo.',
    benefits: ['Plazos de 1 a 5 años', 'Pagos de interés flexibles', 'Respaldo institucional'],
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'tc-clasica',
    name: 'Mastercard Clásica',
    category: 'tarjetas',
    filter: 'credito',
    segment: 'personas',
    rate: 'Sin anualidad 1er año',
    summary: 'Tu primera tarjeta de crédito con control, seguridad y aceptación global.',
    benefits: ['Compras nacionales e internacionales', 'Caja en Línea y app', 'Programa de descuentos'],
    image: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'tc-oro',
    name: 'Mastercard Oro',
    category: 'tarjetas',
    filter: 'credito',
    segment: 'personas',
    rate: 'Beneficios plus',
    summary: 'Más límite, más protecciones y beneficios pensados para tu día a día.',
    benefits: ['Límites más altos', 'Asistencias de viaje', 'Promociones exclusivas'],
    image: 'https://images.unsplash.com/photo-1601597111158-2fceff688771?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'tc-platinum',
    name: 'Mastercard Platinum',
    category: 'tarjetas',
    filter: 'credito',
    segment: 'personas',
    rate: 'Experiencia premium',
    summary: 'La tarjeta que todos quieren: estatus, protecciones y un servicio diferenciado.',
    benefits: ['Sala VIP en aeropuertos seleccionados', 'Concierge', 'Seguros de viaje'],
    image: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'td-mastercard',
    name: 'Débito Mastercard',
    category: 'tarjetas',
    filter: 'debito',
    segment: 'personas',
    rate: 'Vinculada a tu cuenta',
    summary: 'Paga y retira con la red Mastercard, conectada a tu cuenta de ahorros.',
    benefits: ['Compras físicas y en línea', 'Red de cajeros Caja de Ahorros', 'Control en la app'],
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'td-clave',
    name: 'Tarjeta Clave',
    category: 'tarjetas',
    filter: 'debito',
    segment: 'personas',
    rate: 'Red nacional',
    summary: 'La tarjeta clave para retiros y compras en comercios afiliados de Panamá.',
    benefits: ['Retiros en cajeros Clave', 'Compras en comercios locales', 'Bajo costo de mantenimiento'],
    image: 'https://images.unsplash.com/photo-1556742111-a301076d9d18?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'td-juvenil',
    name: 'Débito juvenil',
    category: 'tarjetas',
    filter: 'debito',
    segment: 'personas',
    rate: 'Para jóvenes',
    summary: 'Independencia financiera temprana con controles pensados para la familia.',
    benefits: ['Límites configurables', 'Compras nacionales', 'Educación financiera'],
    image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'prestamo-personal',
    name: 'Préstamo personal',
    category: 'prestamos',
    filter: 'personales',
    segment: 'personas',
    rate: 'Aprobación ágil',
    summary: 'Haz realidad tus metas y proyectos personales con un plan que se adapta a ti.',
    benefits: ['Montos según tu capacidad', 'Desembolso a tu cuenta', 'Cuotas fijas'],
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'prestamo-publico',
    name: 'Préstamo para empleados públicos',
    category: 'prestamos',
    filter: 'personales',
    segment: 'personas',
    rate: 'Condiciones preferentes',
    summary: 'Financiamiento diseñado para colaboradores del sector público.',
    benefits: ['Descuento directo', 'Tasas competitivas', 'Trámite simplificado'],
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'prestamo-privado',
    name: 'Préstamo para empleados privados',
    category: 'prestamos',
    filter: 'personales',
    segment: 'personas',
    rate: 'A tu medida',
    summary: 'Apoyo financiero para quienes trabajan en el sector privado.',
    benefits: ['Evaluación según ingresos', 'Plazos flexibles', 'Caja en Línea'],
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'prendario',
    name: 'Préstamos prendarios',
    category: 'prestamos',
    filter: 'prendarios',
    segment: 'personas',
    rate: 'Usa tu cuenta',
    summary: 'Obtén financiamiento sin retirar tus fondos: usa tus cuentas como garantía.',
    benefits: ['Tus ahorros siguen generando intereses', 'Proceso rápido', 'Sin vender tus depósitos'],
    image: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'hipoteca-preferencial',
    name: 'Vivienda con ley preferencial',
    category: 'prestamos',
    filter: 'hipotecarios',
    segment: 'personas',
    rate: 'Desde 1.50%',
    summary: 'El primer paso hacia tu casa propia con tasas de ley preferencial.',
    benefits: ['Financiamiento de hasta 97%', 'Plazo de hasta 30 años', 'Tasas desde 1.50%'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'traslado-hipoteca',
    name: 'Traslado de hipotecas',
    category: 'prestamos',
    filter: 'hipotecarios',
    segment: 'personas',
    rate: 'Hasta 90%',
    summary: 'Trae tu hipoteca y mejora tus condiciones con un banco que te acompaña.',
    benefits: ['Hasta 90% del avalúo', 'Plazo de hasta 30 años', 'Asesoría personalizada'],
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'terrenos',
    name: 'Compra de terrenos',
    category: 'prestamos',
    filter: 'hipotecarios',
    segment: 'personas',
    rate: 'Hasta 15 años',
    summary: 'Financia el lote donde construirás el proyecto de tu vida.',
    benefits: ['Hasta 60% de financiamiento', 'Plazo de hasta 15 años', 'Asesoría de avalúo'],
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'auto',
    name: 'Préstamo auto regular',
    category: 'prestamos',
    filter: 'autos',
    segment: 'personas',
    rate: 'Planes a tu medida',
    summary: 'Conduce el auto que quieres con tasas competitivas y cuotas cómodas.',
    benefits: ['Autos nuevos y usados', 'Aprobación ágil', 'Planes flexibles'],
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'auto-eco',
    name: 'Préstamo de autos ecológicos',
    category: 'prestamos',
    filter: 'verdes',
    segment: 'personas',
    rate: 'Tasa preferencial',
    summary: 'Estrena un vehículo eléctrico o híbrido con condiciones verdes.',
    benefits: ['Tasas preferenciales', 'Plazos competitivos', 'Aporte a un futuro sostenible'],
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'paneles',
    name: 'Préstamo para paneles solares',
    category: 'prestamos',
    filter: 'verdes',
    segment: 'personas',
    rate: 'Energía limpia',
    summary: 'Financia un techo solar y reduce tu factura eléctrica con respaldo bancario.',
    benefits: ['Proyectos ecoamigables', 'Cuotas alineadas al ahorro energético', 'Asesoría técnica aliada'],
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'casa-mas',
    name: 'Casa Más',
    category: 'prestamos',
    filter: 'hipotecarios',
    segment: 'personas',
    rate: 'Desde 6%',
    summary: 'Préstamo de consumo con garantía hipotecaria para que tus proyectos pasen.',
    benefits: ['Tasa desde 6% fija 5 años', 'Desembolso en 15 días hábiles', 'Avalúo gratis desde $80,000.01'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'prestamo-comercial',
    name: 'Préstamo comercial',
    category: 'prestamos',
    filter: 'empresariales',
    segment: 'empresas',
    rate: 'Capital de trabajo',
    summary: 'Impulsa el crecimiento de tu empresa con financiamiento estructurado.',
    benefits: ['Capital de trabajo', 'Activos fijos', 'Acompañamiento empresarial'],
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'seguro-vida',
    name: 'Seguro de vida',
    category: 'seguros',
    filter: 'proteccion',
    segment: 'personas',
    rate: 'Respaldo familiar',
    summary: 'Protege a quienes más quieres con una cobertura clara y accesible.',
    benefits: ['Cobertura por fallecimiento', 'Opciones de capital asegurado', 'Acompañamiento en el reclamo'],
    image: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'seguro-incendio',
    name: 'Seguro de incendio',
    category: 'seguros',
    filter: 'proteccion',
    segment: 'personas',
    rate: 'Tu patrimonio',
    summary: 'Resguarda tu vivienda frente a incendio y riesgos asociados.',
    benefits: ['Cobertura de estructura', 'Opciones de contenido', 'Requisito habitual de hipoteca'],
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'seguro-auto',
    name: 'Seguro de auto',
    category: 'seguros',
    filter: 'proteccion',
    segment: 'personas',
    rate: 'Al volante',
    summary: 'Circula con tranquilidad: daños, robo y responsabilidad civil.',
    benefits: ['Daños propios y a terceros', 'Asistencia vial', 'Red de talleres'],
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=900&q=80',
  },
  {
    slug: 'asistencia-medica',
    name: 'Asistencia médica',
    category: 'seguros',
    filter: 'asistencias',
    segment: 'personas',
    rate: 'Cuando más importa',
    summary: 'Orientación y apoyo médico para ti y tu familia, cuando lo necesitas.',
    benefits: ['Orientación telefónica', 'Red de aliados', 'Complemento a tus productos'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=80',
  },
]

export const catalogMeta = {
  cuentas: {
    title: 'Todas las cuentas',
    kicker: 'Cuentas',
    lead: 'Elige el tipo de cuenta que mejor se adapta a ti. Filtra por categoría y encuentra beneficios a tu medida.',
    filters: [
      { id: 'todos', label: 'Todos' },
      { id: 'ahorros', label: 'Ahorros' },
      { id: 'corrientes', label: 'Corrientes' },
      { id: 'plazo', label: 'Plazo fijo' },
      { id: 'digitales', label: 'Digitales' },
      { id: 'empresariales', label: 'Empresariales' },
    ],
  },
  tarjetas: {
    title: 'Tarjetas',
    kicker: 'Tarjetas',
    lead: 'Crédito o débito: elige la plástica que se mueve contigo, en Panamá y en el mundo.',
    filters: [
      { id: 'todos', label: 'Todos' },
      { id: 'credito', label: 'Crédito' },
      { id: 'debito', label: 'Débito' },
    ],
  },
  prestamos: {
    title: 'Préstamos',
    kicker: 'Préstamos',
    lead: 'Explora opciones de consumo, vivienda, auto y financiamiento verde. Elige la categoría de tu interés.',
    filters: [
      { id: 'todos', label: 'Todos' },
      { id: 'personales', label: 'Personales' },
      { id: 'hipotecarios', label: 'Hipotecarios' },
      { id: 'autos', label: 'Autos' },
      { id: 'verdes', label: 'Verdes' },
      { id: 'prendarios', label: 'Prendarios' },
      { id: 'empresariales', label: 'Empresariales' },
    ],
  },
  seguros: {
    title: 'Seguros y asistencias',
    kicker: 'Protección',
    lead: 'Complementa tus productos con coberturas que cuidan tu patrimonio, tu familia y tu movilidad.',
    filters: [
      { id: 'todos', label: 'Todos' },
      { id: 'proteccion', label: 'Protección' },
      { id: 'asistencias', label: 'Asistencias' },
    ],
  },
}

export const properties = [
  {
    id: 'p1',
    tipo: 'nuevas',
    title: 'Residencial Costa Verde',
    place: 'Costa del Este, Panamá',
    price: 'Desde B/. 185,000',
    beds: 3,
    baths: 2,
    area: '128 m²',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'p2',
    tipo: 'nuevas',
    title: 'Torres del Pacífico',
    place: 'San Francisco, Panamá',
    price: 'Desde B/. 210,000',
    beds: 2,
    baths: 2,
    area: '96 m²',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'p3',
    tipo: 'reposeidas',
    title: 'Casa en Brisas del Golf',
    place: 'Panamá Este',
    price: 'B/. 142,000',
    beds: 3,
    baths: 2,
    area: '140 m²',
    image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'p4',
    tipo: 'reposeidas',
    title: 'Apartamento Vía España',
    place: 'Bella Vista',
    price: 'B/. 98,500',
    beds: 2,
    baths: 1,
    area: '78 m²',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'p5',
    tipo: 'nuevas',
    title: 'Casa de playa Coronado',
    place: 'Coronado, Panamá Oeste',
    price: 'Desde B/. 265,000',
    beds: 4,
    baths: 3,
    area: '210 m²',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'p6',
    tipo: 'reposeidas',
    title: 'Townhouse Albrook',
    place: 'Ancón, Panamá',
    price: 'B/. 168,900',
    beds: 3,
    baths: 2.5,
    area: '155 m²',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cd24?auto=format&fit=crop&w=1000&q=80',
  },
]

export const news = [
  {
    slug: 'alianza-fintech',
    date: '26 de agosto de 2026',
    title: 'Caja de Ahorros impulsa una alianza estratégica con la Cámara Fintech de Panamá',
  },
  {
    slug: 'sostenibilidad-gobernanza',
    date: '24 de agosto de 2026',
    title: 'Diálogo sobre sostenibilidad y gobernanza corporativa en Panamá',
  },
  {
    slug: 'inclusion-financiera',
    date: '24 de agosto de 2026',
    title: 'Inclusión financiera: alianzas con organismos internacionales',
  },
  {
    slug: 'apc-experian',
    date: '20 de agosto de 2026',
    title: 'Alianza con APC Experian para educación financiera e innovación tecnológica',
  },
  {
    slug: 'informe-sostenibilidad',
    date: '18 de agosto de 2026',
    title: 'Informe de Sostenibilidad 2025: compromiso renovado con el país',
  },
  {
    slug: 'hackathon-2026',
    date: '13 de agosto de 2026',
    title: 'Primer Hackathon 2026 enfocado en data e inteligencia artificial',
  },
]

export const faqs = [
  {
    q: '¿Cómo abro una cuenta de ahorro o corriente?',
    a: 'Puedes iniciar en línea desde Cuentas: elige el producto, completa la solicitud o ábrela de inmediato si es una cuenta digital. También puedes hacerlo en sucursal con cédula o pasaporte vigente.',
  },
  {
    q: '¿Dónde están las sucursales y cajeros más cercanos?',
    a: 'Usa el buscador de sucursales en Servicios. Ingresa tu zona o explora el listado con horarios y si el punto tiene cajero automático.',
  },
  {
    q: '¿Cómo accedo a la banca en línea o recupero mi usuario?',
    a: 'Entra a Banca en línea desde el botón superior. Si olvidaste tus credenciales, usa “Olvidé mi usuario o clave” en la pantalla de acceso y sigue los pasos de verificación.',
  },
  {
    q: '¿Puedo abrir una cuenta 100% digital?',
    a: 'Sí. Están disponibles las cuentas digitales Infantil, Juvenil, Panamá para ti, Navidad y Ahorro Caja en línea, sujeto a validación de identidad.',
  },
]

export const branches = [
  { name: 'Casa Matriz', place: 'Vía España, Panamá', hours: 'Lun–Vie 8:00 a. m. – 3:00 p. m.', atm: true },
  { name: 'Albrook Mall', place: 'Albrook, Ancón', hours: 'Lun–Sáb 10:00 a. m. – 7:00 p. m.', atm: true },
  { name: 'Costa del Este', place: 'Town Center, Costa del Este', hours: 'Lun–Vie 9:00 a. m. – 5:00 p. m.', atm: true },
  { name: 'David', place: 'Av. 3a Este, Chiriquí', hours: 'Lun–Vie 8:00 a. m. – 3:00 p. m.', atm: true },
  { name: 'Santiago', place: 'Calle Central, Veraguas', hours: 'Lun–Vie 8:00 a. m. – 3:00 p. m.', atm: false },
  { name: 'Colón 2000', place: 'Colón', hours: 'Lun–Vie 8:30 a. m. – 3:30 p. m.', atm: true },
]
